### ISSUE TITLE
A way to remove collection.flatMap from every query

### ISSUE THREAD

**Issue by jyotman** [ricsirigu/play26-swagger-reactivemongo#1]
Hi, I was wondering if there's a way to resolve the collection Future. If in Todo.scala model, this -
```scala
def collection: Future[JSONCollection]
```
could be converted to -
```scala
def collection: JSONCollection
```
Then in every query we could remove the `collection.flatMap`. 

Example -
```scala
def addTodo(todo: Todo): Future[WriteResult] = {
   collection.flatMap(_.insert(todo))
}
```
would become - 
```scala
def addTodo(todo: Todo): Future[WriteResult] = {
  collection.insert(todo)
}
```

**Comment by ricsirigu** [comment]
@jyotman yes you can but you [shouldn't](https://docs.scala-lang.org/overviews/core/futures.html#futures).
You can call `.result` on the future or use [scala-async](https://github.com/scala/scala-async)
