### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by RBleyenberg** [ricsirigu/play26-swagger-reactivemongo#3]
Howdy,

first many thx for this use case with swagger and play

My question is... do you have maybe a example on how to use storage for images upload within a mongo document  ect.  maybe even extend your todo with attachments as example.

i can't find any examples for play mongo crud with images/attachments and really like to see some best practice thingy, if possible with swagger as wrapper around it.. that would be awesome.

Best regards,

**Comment by ricsirigu** [comment]
Hi @RBleyenberg.
I don't like storing binary files in MongoDb, I usually upload them on a cloud storage service such as Amazon S3 and then storing the link on the database.

If you really need to store binary files on MongoDb you can take a look at [GridFs](https://docs.mongodb.com/manual/core/gridfs/) and [ReactiveMongo with GridFs](http://reactivemongo.org/releases/0.12/documentation/advanced-topics/gridfs.html) 

I don't know when I'll have time to build an example.
Try building a project and I can help you from there

**Comment by RBleyenberg** [comment]
Howdy,

 i took a look at gridFs and it's awesome for what i need/want.

Thanks... for the link and responds

**Comment by ricsirigu** [comment]
@RBleyenberg you are welcome, I'm closing this issue
