### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by sarathraj-coder** [ricsirigu/play26-swagger-reactivemongo#5]
No Json serializer found for type Seq[models.Todo]. Try to implement an implicit Writes or Format for this type.

**Comment by ricsirigu** [comment]
Hi @sarathraj-coder , thank you for the feedback.
How can I reproduce the bug?

**Comment by sarathraj-coder** [comment]
its fixed i added companion object in the model instead of  object JsonFormats
object Todo{
  import  play.api.libs.json._
  implicit val todoFormat: OFormat[Todo] = Json.format[Todo]
}

**Comment by ricsirigu** [comment]
Great
