### ISSUE TITLE
No instance of play.api.libs.json.Format is available for scala.Option[reactivemongo.bson.BSONObjectID] 

### ISSUE THREAD

**Issue by maelfosso** [ricsirigu/play26-swagger-reactivemongo#6]
Hi,

I'm a newbie in PlayFramework

I got this error 
```
No instance of play.api.libs.json.Format is available for scala.Option[reactivemongo.bson.BSONObjectID] in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
```

How to solve it please ?

**Comment by ricsirigu** [comment]
Try with `import reactivemongo.play.json.BSONFormats`

**Comment by ricsirigu** [comment]
Sorry but I'm closing this issue because it's not relevant to this repository.

If you have any other questions ask [here](https://groups.google.com/forum/#!forum/reactivemongo)
